/*
 * (c) 2019 Copyright, Real-Time Innovations, Inc.  All rights reserved.
 *
 * RTI grants Licensee a license to use, modify, compile, and create derivative
 * works of the Software.  Licensee has the right to distribute object form
 * only for use with RTI products.  The Software is provided "as is", with no
 * warranty of any type, including any warranty for fitness for any purpose.
 * RTI is under no obligation to maintain or support the Software.  RTI shall
 * not be liable for any incidental or consequential damages arising out of the
 * use or inability to use the software.
 */
 
module rti { module prcs { module fwd {

    @nested
    struct MatchingTableEntry {
        string in_key;
        string out_name;
    };

    @nested
    struct MatchingTable {
        sequence<MatchingTableEntry> entries;
    };

    typedef MatchingTable   ForwardingTable;
    typedef MatchingTable   InputMembersTable;

    @appendable
    struct ForwardingEngineConfiguration {
        ForwardingTable fwd_table;
    };

    struct ByInputNameForwardingEngineConfiguration : ForwardingEngineConfiguration {
        // no additional fields defined for now.
    };

    struct ByInputValueForwardingEngineConfiguration : ForwardingEngineConfiguration {
        InputMembersTable input_members;
    };

};  };  };