#
# (c) 2019 Copyright, Real-Time Innovations, Inc.  All rights reserved.
#
# RTI grants Licensee a license to use, modify, compile, and create derivative
# works of the Software.  Licensee has the right to distribute object form
# only for use with RTI products.  The Software is provided "as is", with no
# warranty of any type, including any warranty for fitness for any purpose.
# RTI is under no obligation to maintain or support the Software.  RTI shall
# not be liable for any incidental or consequential damages arising out of the
# use or inability to use the software.
# 
RSHELPER_DIR			?= ../rtiroutingservice-plugin-helper

RSPLUGIN_ROOT           := $(shell pwd)
RSPLUGIN_PREFIX			:= RTI_PRCS_MAP
RSPLUGIN_NAME			:= rtiroutingservice-processor-cbr
RSPLUGIN_NEEDS_CONFIG	:= y
TESTER_PREFIX 			:= rtiprcscbr_

include $(RSHELPER_DIR)/make/rtiroutingservice_plugin_env.mk
include $(RSHELPER_DIR)/make/rtiroutingservice_plugin_targets.mk